import "~/styles/globals.css";

import { type Metadata } from "next";
import { Architects_Daughter } from "next/font/google";

import Providers from "~/components/providers";
import { getAppConfig } from "~/data-access/appconf";
import Header from "~/app/(app)/components/Header";
import Footer from "~/app/(app)/components/Footer";
import type { Media } from "@payload-types";
import seoToMetadata from "~/lib/seo-to-metadata";
import { Suspense } from "react";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export async function generateMetadata(): Promise<Metadata> {
  const appConfig = await getAppConfig();
  const seo = appConfig.seo || {};

  return {
    ...seoToMetadata(seo),
    icons: {
      icon: (appConfig.favicon as Media).url ?? "/favicon.ico",
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const appConfig = await getAppConfig();
  return (
    <Suspense fallback={"loading..."}>
      <Header appConfig={appConfig} />

      <main className={"flex-1"}>
        <Providers>{children}</Providers>
      </main>
      <Footer />
    </Suspense>
  );
}
