version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5101:5432"
    volumes:
      - db_data:/var/lib/postgresql/data1

volumes:
  db_data: