version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydbs
    ports:
      - "5102:5432"
    volumes:
      - db_data:/var/lib/postgresql/data14
  adminer:
    image: adminer
    container_name: adminer-blog-nonprofit
    ports:
      - "7071:8080"

volumes:
  db_data: