import "~/styles/globals.css";

import { type Metadata } from "next";
import { Architects_Daughter} from "next/font/google";

import Providers from "~/components/providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Architects_Daughter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ['400']
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${font.variable}`} suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
